// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package dbgen

import (
	"context"
)

const archiveItem = `-- name: ArchiveItem :exec
UPDATE items SET archived = 1, updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) ArchiveItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveItem, id)
	return err
}

const countDueForReview = `-- name: CountDueForReview :one
SELECT COUNT(*) FROM items WHERE archived = 0 AND next_review <= datetime('now')
`

func (q *Queries) CountDueForReview(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDueForReview)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (item_type, title, content, done, priority, due_date, tags, next_review, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'), datetime('now'))
RETURNING id, item_type, title, content, done, priority, due_date, tags, ease_factor, interval_days, repetitions, next_review, last_reviewed, created_at, updated_at, archived
`

type CreateItemParams struct {
	ItemType string  `json:"item_type"`
	Title    string  `json:"title"`
	Content  string  `json:"content"`
	Done     int64   `json:"done"`
	Priority int64   `json:"priority"`
	DueDate  *string `json:"due_date"`
	Tags     string  `json:"tags"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.ItemType,
		arg.Title,
		arg.Content,
		arg.Done,
		arg.Priority,
		arg.DueDate,
		arg.Tags,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ItemType,
		&i.Title,
		&i.Content,
		&i.Done,
		&i.Priority,
		&i.DueDate,
		&i.Tags,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.LastReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, item_type, title, content, done, priority, due_date, tags, ease_factor, interval_days, repetitions, next_review, last_reviewed, created_at, updated_at, archived FROM items WHERE id = ? AND archived = 0
`

func (q *Queries) GetItem(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ItemType,
		&i.Title,
		&i.Content,
		&i.Done,
		&i.Priority,
		&i.DueDate,
		&i.Tags,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.LastReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const listDueForReview = `-- name: ListDueForReview :many
SELECT id, item_type, title, content, done, priority, due_date, tags, ease_factor, interval_days, repetitions, next_review, last_reviewed, created_at, updated_at, archived FROM items WHERE archived = 0 AND next_review <= datetime('now') ORDER BY next_review ASC
`

func (q *Queries) ListDueForReview(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listDueForReview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ItemType,
			&i.Title,
			&i.Content,
			&i.Done,
			&i.Priority,
			&i.DueDate,
			&i.Tags,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReview,
			&i.LastReviewed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotes = `-- name: ListNotes :many
SELECT id, item_type, title, content, done, priority, due_date, tags, ease_factor, interval_days, repetitions, next_review, last_reviewed, created_at, updated_at, archived FROM items WHERE item_type = 'note' AND archived = 0 ORDER BY updated_at DESC
`

func (q *Queries) ListNotes(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ItemType,
			&i.Title,
			&i.Content,
			&i.Done,
			&i.Priority,
			&i.DueDate,
			&i.Tags,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReview,
			&i.LastReviewed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
SELECT id, item_type, title, content, done, priority, due_date, tags, ease_factor, interval_days, repetitions, next_review, last_reviewed, created_at, updated_at, archived FROM items WHERE item_type = 'todo' AND archived = 0 ORDER BY done ASC, priority DESC, created_at DESC
`

func (q *Queries) ListTodos(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ItemType,
			&i.Title,
			&i.Content,
			&i.Done,
			&i.Priority,
			&i.DueDate,
			&i.Tags,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReview,
			&i.LastReviewed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewItem = `-- name: ReviewItem :one
UPDATE items SET ease_factor = ?, interval_days = ?, repetitions = ?, next_review = ?, last_reviewed = datetime('now'), updated_at = datetime('now')
WHERE id = ? AND archived = 0
RETURNING id, item_type, title, content, done, priority, due_date, tags, ease_factor, interval_days, repetitions, next_review, last_reviewed, created_at, updated_at, archived
`

type ReviewItemParams struct {
	EaseFactor   float64 `json:"ease_factor"`
	IntervalDays float64 `json:"interval_days"`
	Repetitions  int64   `json:"repetitions"`
	NextReview   string  `json:"next_review"`
	ID           int64   `json:"id"`
}

func (q *Queries) ReviewItem(ctx context.Context, arg ReviewItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, reviewItem,
		arg.EaseFactor,
		arg.IntervalDays,
		arg.Repetitions,
		arg.NextReview,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ItemType,
		&i.Title,
		&i.Content,
		&i.Done,
		&i.Priority,
		&i.DueDate,
		&i.Tags,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.LastReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const searchItems = `-- name: SearchItems :many
SELECT id, item_type, title, content, done, priority, due_date, tags, ease_factor, interval_days, repetitions, next_review, last_reviewed, created_at, updated_at, archived FROM items WHERE archived = 0 AND (title LIKE '%' || ? || '%' OR content LIKE '%' || ? || '%') ORDER BY updated_at DESC
`

type SearchItemsParams struct {
	Column1 *string `json:"column_1"`
	Column2 *string `json:"column_2"`
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, searchItems, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ItemType,
			&i.Title,
			&i.Content,
			&i.Done,
			&i.Priority,
			&i.DueDate,
			&i.Tags,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.NextReview,
			&i.LastReviewed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTodoDone = `-- name: ToggleTodoDone :one
UPDATE items SET done = CASE WHEN done = 0 THEN 1 ELSE 0 END, updated_at = datetime('now')
WHERE id = ? AND item_type = 'todo' AND archived = 0
RETURNING id, item_type, title, content, done, priority, due_date, tags, ease_factor, interval_days, repetitions, next_review, last_reviewed, created_at, updated_at, archived
`

func (q *Queries) ToggleTodoDone(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRowContext(ctx, toggleTodoDone, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ItemType,
		&i.Title,
		&i.Content,
		&i.Done,
		&i.Priority,
		&i.DueDate,
		&i.Tags,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.LastReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE items SET title = ?, content = ?, priority = ?, due_date = ?, tags = ?, updated_at = datetime('now')
WHERE id = ? AND archived = 0
RETURNING id, item_type, title, content, done, priority, due_date, tags, ease_factor, interval_days, repetitions, next_review, last_reviewed, created_at, updated_at, archived
`

type UpdateItemParams struct {
	Title    string  `json:"title"`
	Content  string  `json:"content"`
	Priority int64   `json:"priority"`
	DueDate  *string `json:"due_date"`
	Tags     string  `json:"tags"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem,
		arg.Title,
		arg.Content,
		arg.Priority,
		arg.DueDate,
		arg.Tags,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ItemType,
		&i.Title,
		&i.Content,
		&i.Done,
		&i.Priority,
		&i.DueDate,
		&i.Tags,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.NextReview,
		&i.LastReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}
