// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Item struct {
	ID           int64   `json:"id"`
	ItemType     string  `json:"item_type"`
	Title        string  `json:"title"`
	Content      string  `json:"content"`
	Done         int64   `json:"done"`
	Priority     int64   `json:"priority"`
	DueDate      *string `json:"due_date"`
	Tags         string  `json:"tags"`
	EaseFactor   float64 `json:"ease_factor"`
	IntervalDays float64 `json:"interval_days"`
	Repetitions  int64   `json:"repetitions"`
	NextReview   string  `json:"next_review"`
	LastReviewed *string `json:"last_reviewed"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	Archived     int64   `json:"archived"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
