[linters]
enable-all = true
disable = [
    "gci", # doesn't play nicely with goimports
    "ifshort", # I'd rather be explicit about exec-ing commands and responding to them
    "forbidigo", # I print output on purpose
    "ireturn", # I return generic types
]

[issues]
fix = true
